name: Teensy Upload and Serial Monitor

on: [push, workflow_dispatch]

jobs:
  upload:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
        with:
          clean: false
      
      - name: Upload to Teensy
        run: pio run -t upload
      
      - name: Monitor Serial Output
        run: |
          sleep 5
          timeout 10s cat /dev/serial/by-id/usb-Teensyduino_USB_Serial_11419230-if00 > serial_output.log || true
      
      - name: Upload Serial Log as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: serial-log
          path: serial_output.log
          retention-days: 7