name: Teensy Upload and Serial Monitor

on: [push, workflow_dispatch]

jobs:
  upload:
    runs-on: self-hosted
    container:
      image: petewall/platformio
      options: --device /dev/serial/by-id/usb-Teensyduino_USB_Serial_11419230-if00:/dev/ttyACM0 --env="DISPLAY" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload to Teensy
        run: pio run -t upload
      
      - name: Monitor Serial Output
        run: |
          timeout 5s cat /dev/ttyACM0