name: Teensy Upload and Serial Monitor

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      baud_rate:
        description: 'Serial baud rate'
        required: true
        default: '9600'
        type: number
      timeout:
        description: 'Serial monitor timeout (seconds)'
        required: true
        default: 5
        type: number

jobs:
  upload:
    runs-on: self-hosted
    container:
      image: petewall/platformio
      options: --device /dev/serial/by-id/usb-Teensyduino_USB_Serial_11419230-if00
    steps:
      - uses: actions/checkout@v4
      
      - name: Upload to Teensy
        run: pio run -t upload
      
      - name: Monitor Serial Output
        run: |
          timeout ${{ github.event.inputs.timeout }}s cat /dev/serial/by-id/usb-Teensyduino_USB_Serial_11419230-if00