name: Teensy Upload and Serial Monitor

on: [push, workflow_dispatch]

jobs:
  upload:
    runs-on: self-hosted
    container:
      image: petewall/platformio
      options: --device /dev/serial/by-id/usb-Teensyduino_USB_Serial_11419230-if00:/dev/ttyACM0 --env="DISPLAY" --volume="/tmp/.X11-unix:/tmp/.X11-unix:rw"
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Teensy udev rules
        run: |
          # Temporarily disable strict checking for apt repositories
          mkdir -p /etc/apt/apt.conf.d/
          echo 'Acquire::AllowInsecureRepositories "true";' > /etc/apt/apt.conf.d/99allow-insecure
          echo 'Acquire::AllowDowngradeToInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99allow-insecure
          
          # Update and install wget without strict repository checking
          apt-get update --allow-insecure-repositories
          apt-get install -y --allow-unauthenticated wget
          
          # Download and set up Teensy rules
          wget -O /etc/udev/rules.d/49-teensy.rules https://www.pjrc.com/teensy/00-teensy.rules
          udevadm control --reload-rules
          udevadm trigger
        shell: bash
      
      - name: Upload to Teensy
        run: pio run -t upload
      
      - name: Monitor Serial Output
        run: |
          timeout 5s cat /dev/ttyACM0 || true